name: Documentation

on:
  push:
    tags:
    - '*'
  workflow_dispatch:

jobs:
  docs-gen:
    name: Doxygen
    runs-on: ubuntu-latest
    
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Clone Doxgen Awesome CSS"
        uses: actions/checkout@v2
        with:
          repository: jothepro/doxygen-awesome-css
          ref: v1.6.0
          clean: false
          path: "./"

      - name: Compute version
        id: version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      
      - name: "Run Doxygen"
        uses: mattnotmitt/doxygen-action@v1.1.0
        with:
          working-directory: "./docs"

      - name: "Deploy Documentation"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
          full_commit_message: "Deploy ${{ steps.version.outputs.VERSION }} Documentation"