name: Documentation

on:
  push:
    tags:
    - '*'
  workflow_dispatch:

jobs:
  docs-gen:
    name: Doxygen
    runs-on: ubuntu-latest
    
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Run Doxygen"
        uses: mattnotmitt/doxygen-action@v1.1.0
        with:
          working-directory: "./docs"

      - name: "Deploy Documentation"
        uses: peaceiris/actions-gh-pages@v3
        with:
          force_orphan: true
          publish_dir: ./docs/html
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "Deploy Documentation"